CREATE DATABASE QLBH
USE QLBH

CREATE TABLE KHACHHANG(
	MAKH CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	DOANHSO MONEY,
	NGDK SMALLDATETIME,
	CONSTRAINT PK_KH PRIMARY KEY(MAKH)
)

CREATE TABLE NHANVIEN(
	MANV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
	CONSTRAINT PK_NV PRIMARY KEY(MANV)
)

CREATE TABLE SANPHAM(
	MASP CHAR(4) NOT NULL,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY,
	CONSTRAINT PK_SP PRIMARY KEY(MASP)
)

CREATE TABLE HOADON(
	SOHD INT,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA MONEY,
	CONSTRAINT PK_HD PRIMARY KEY(SOHD),
	CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE CTHD(
	SOHD INT,
	MASP CHAR(4),
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MASP),
	CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)
ALTER TABLE CTHD add CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
INSERT INTO CTHD VALUES(1001,'null',10)



---------------------------------------------------------------------------------------


/* I. Ngon ngu dinh nghia du lieu */

-- 2. Them thuoc tinh GHICHU VARCHAR(20) vao SANPHAM
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)

-- 3. Them thuoc tinh LOAIKH TINYINT vao KHACHHANG
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT

-- 4. Sua kieu du lieu thuoc tinh GHICHU trong SANPHAM thanh VARCHAR(100)
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)

-- 5. Xoa thuoc tinh GHICHU trong SANPHAM
ALTER TABLE SANPHAM DROP COLUMN GHICHU

-- 6. Doi thuoc tinh LOAIKH trong KHACHHANG thanh VARCHAR(20)
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20)

-- 7. Don vi tinh cua san pham chi co the la ("cay", "hop", "cai", "quyen", "chuc")
ALTER TABLE SANPHAM ADD CONSTRAINT CHK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))

-- 8. Gia ban cua sp tu 500 dong tro len
ALTER TABLE SANPHAM ADD CONSTRAINT CHK_GIA CHECK (GIA > 500)

-- 9. Moi lan mua, khach hang phai mua it nhat 1 sp
ALTER TABLE CTHD ADD CONSTRAINT CHK_SL CHECK (SL >= 1)

-- 10. Ngay dk khach hang thanh vien > ngay sinh
ALTER TABLE KHACHHANG ADD CONSTRAINT CHK_NGDK CHECK (NGDK > NGSINH)





----------------------------------------------------/* LAB 5: I.11 -> I.15 */------------------------------------------------------------------------------------------



-- 11. Ngày mua hàng (NGHD) của khách hàng thành viên >= ngày đăng ký thành viên (NGDK).
--				THEM	XOA		SUA
-- KHACHHANG	 -		 -		 + (NGDK)
-- HOADON		 +		 -		 + (NGHD)

-- insert HOADON
CREATE TRIGGER trg_insert_hd_c11 ON HOADON
AFTER INSERT 
AS BEGIN
	DECLARE @NGHD SMALLDATETIME, @NGDK SMALLDATETIME, @MAKH CHAR(4)
	SELECT @NGHD = NGHD, @MAKH = MAKH FROM inserted
	SELECT @NGDK FROM KHACHHANG WHERE MAKH = @MAKH
	IF (@NGHD < @NGDK)
	BEGIN
		PRINT 'ERROR: NGAY KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM DU LIEU THANH CONG'
	END
END


-- update HOADON
CREATE TRIGGER trg_update_hd_c11 ON HOADON
AFTER UPDATE
AS BEGIN
	DECLARE @NGHD SMALLDATETIME, @NGDK SMALLDATETIME, @MAKH CHAR(4)
	SELECT @NGHD = NGHD, @MAKH = MAKH FROM inserted
	SELECT @NGDK FROM KHACHHANG WHERE NGDK = @NGDK
	IF (@NGHD < @NGDK)
	BEGIN
		PRINT 'ERROR: NGAY KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'CAP NHAT DU LIEU THANH CONG'
	END
END

-- update KHACHHANG
CREATE TRIGGER trg_update_kh_c11 ON KHACHHANG
AFTER UPDATE
AS BEGIN
	DECLARE @NGHD SMALLDATETIME, @NGDK SMALLDATETIME, @MAKH CHAR(4)
	SELECT @NGDK = NGDK, @MAKH = MAKH FROM inserted
	SELECT @NGHD FROM KHACHHANG WHERE MAKH = @MAKH
	IF (@NGDK < @NGHD)
	BEGIN
		PRINT 'ERROR: NGAY KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'CAP NHAT DU LIEU THANH CONG'
	END
END


-- 12. Ngày bán hàng (NGHD) của một nhân viên >= ngày nhân viên đó vào làm. 
--				THEM	XOA		SUA
-- NHANVIEN		 -		 -		 + (NGVL)
-- HOADON		 +		 -		 + (NGHD)

-- insert HOADON
CREATE TRIGGER trg_insert_hd_c12 ON HOADON
AFTER INSERT
AS BEGIN
	DECLARE @NGVL SMALLDATETIME, @NGHD SMALLDATETIME, @MANV CHAR(4)
	SELECT @NGHD = NGHD, @MANV = MANV FROM inserted
	SELECT @NGVL = NGVL FROM NHANVIEN WHERE MANV = @MANV
	IF (@NGHD < @NGVL)
	BEGIN
		PRINT 'ERROR: NGAY KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM DU LIEU THANH CONG'
	END
END


-- update HOADON
CREATE TRIGGER trg_update_hd_c12 ON HOADON
AFTER INSERT
AS BEGIN
	DECLARE @NGVL SMALLDATETIME, @NGHD SMALLDATETIME, @MANV CHAR(4)
	SELECT @NGHD = NGHD, @MANV = MANV FROM inserted
	SELECT @NGVL = NGVL FROM NHANVIEN WHERE MANV = @MANV
	IF (@NGHD < @NGVL)
	BEGIN
		PRINT 'ERROR: NGAY KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'CAP NHAT DU LIEU THANH CONG'
	END
END

-- update NHANVIEN
CREATE TRIGGER trg_update_nv_c12 ON NHANVIEN
AFTER INSERT
AS BEGIN
	DECLARE @NGVL SMALLDATETIME, @NGHD SMALLDATETIME, @MANV CHAR(4)
	SELECT @NGVL = NGVL, @MANV = MANV FROM inserted
	SELECT @NGHD = NGHD FROM HOADON WHERE MANV = @MANV
	IF (@NGHD < @NGVL)
	BEGIN
		PRINT 'ERROR: NGAY KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'CAP NHAT DU LIEU THANH CONG'
	END
END



-- 13. Mỗi một hóa đơn phải có ít nhất một chi tiết hóa đơn. 
--				THEM	XOA		SUA
-- HOADON		 +		 -		 - (*)
-- CTHD			 -		 +		 + 

-- insert HOADON
CREATE TRIGGER trg_insert_hd_c13 ON HOADON
AFTER INSERT
AS BEGIN
	DECLARE @SOHD INT
	SELECT @SOHD = SOHD FROM inserted
	INSERT INTO CTHD VALUES (@SOHD, 'bb01', 1)
	PRINT 'THEM HOA DON THANH CONG. UPDATE LAI CTHD'
END

-- delete update CTHD
CREATE TRIGGER trg_delete_update_cthd_c13 ON CTHD
AFTER DELETE
AS BEGIN
	DECLARE @SL INT, @SOHD INT
	SELECT  @SOHD = SOHD FROM deleted
	SELECT @SL = COUNT(SOHD) FROM CTHD
	WHERE SOHD = @SOHD
	GROUP BY SOHD
	IF (@SL < 1)
	BEGIN
		DELETE FROM HOADON
		WHERE SOHD = @SOHD
		PRINT 'DA DELETE CTHD CUOI CUNG CUA HOADON'
	END
END


-- 14. Trị giá của một hóa đơn là tổng thành tiền (số lượng*đơn giá) của các chi tiết thuộc hóa đơn đó. 
--				THEM	XOA		SUA
-- HOADON		 +		 -		 +
-- CTHD			 +		 +		 + 

-- insert HOADON
CREATE TRIGGER trg_insert_hd_c14 ON HOADON
AFTER INSERT
AS BEGIN
	UPDATE HOADON
	SET TRIGIA = 0
	WHERE SOHD = (	SELECT SOHD FROM INSERTED)
	PRINT 'DA INSERT 1 HOADON TRIGIA BAN DAU LA 0 VND'
END

-- update HOADON
ALTER TRIGGER trg_update_hd_c14 ON HOADON
AFTER UPDATE
AS BEGIN
	DECLARE @TRIGIA_D MONEY, @TRIGIA_I MONEY
	SELECT @TRIGIA_D = TRIGIA FROM DELETED
	SELECT @TRIGIA_I = TRIGIA FROM INSERTED
	IF (@TRIGIA_I = @TRIGIA_D)
	BEGIN
		PRINT 'DA UPDATE 1 HOADON VOI TRIGIA KHONG THAY DOI'
	END
	ELSE
	BEGIN
		PRINT 'UPDATE THAT BAI DO THAY DOI TRIGIA'
	END
END

-- insert CTHD
CREATE TRIGGER trg_insert_cthd_c14 ON CTHD
AFTER INSERT 
AS BEGIN
	DECLARE @SL INT, @GIA MONEY, @SOHD INT, @MASP CHAR(4)
	SELECT @SL = SL, @MASP = MASP, @SOHD = SOHD FROM INSERTED
	SELECT @GIA = GIA FROM SANPHAM WHERE MASP = @MASP

	UPDATE HOADON
	SET TRIGIA = TRIGIA + @SL * @GIA
	PRINT 'DA INSERT 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
END

-- delete CTHD
CREATE TRIGGER trg_delete_cthd_c14 ON CTHD
AFTER DELETE
AS BEGIN
	DECLARE @SL INT, @GIA MONEY, @SOHD INT, @MASP CHAR(4)
	SELECT @SL = SL, @SOHD = SOHD, @MASP = MASP FROM INSERTED
	SELECT @GIA = GIA FROM SANPHAM WHERE MASP = @MASP

	UPDATE HOADON
	SET TRIGIA = TRIGIA - @SL * @GIA
	WHERE SOHD = @SOHD
	PRINT 'DA INSERT 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
END

-- update CTHD
CREATE TRIGGER trg_update_cthd_c14 ON CTHD
AFTER UPDATE
AS BEGIN
	DECLARE @SL_CU INT, @GIA_CU MONEY, @SOHD_CU INT,
			@SL_MOI INT, @GIA_MOI MONEY, @SOHD_MOI INT

	SELECT @GIA_CU=GIA,@SL_CU=SL,@SOHD_CU=SOHD 
	FROM  DELETED D, SANPHAM SP 
	WHERE D.MASP=SP.MASP 
  
	SELECT @GIA_MOI=GIA,@SL_MOI=SL,@SOHD_MOI=SOHD 
	FROM  INSERTED I, SANPHAM SP 
	WHERE I.MASP=SP.MASP 

	IF (@SOHD_CU = @SOHD_MOI)
	BEGIN
		UPDATE HOADON
		SET TRIGIA = TRIGIA - @SL_CU * @GIA_CU + @SL_MOI * @GIA_MOI
		WHERE SOHD = @SOHD_CU
	END
	ELSE
	BEGIN
		UPDATE HOADON
		SET TRIGIA =  TRIGIA - @SL_CU * @GIA_CU
		WHERE SOHD = @SOHD_CU
		UPDATE HOADON
		SET TRIGIA =  TRIGIA + @SL_MOI * @GIA_MOI
		WHERE SOHD = @SOHD_MOI
	END
	PRINT 'DA UPDATE LAI 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
END





-- 15. Doanh số của một khách hàng là tổng trị giá các hóa đơn mà khách hàng thành viên đó đã mua. 
--				THEM	XOA		SUA
-- KHACHHANG	 +		 -		 +
-- HOADON		 +		 +		 +

-- insert KHACHHANG
CREATE TRIGGER trg_insert_kh_c15 ON KHACHHANG
AFTER INSERT
AS BEGIN
	UPDATE KHACHHANG
	SET DOANHSO = 0
	WHERE MAKH = (	SELECT MAKH FROM inserted	)
	PRINT 'DA THEM KHACHHANG MOI VOI DOANHSO BAN DAU LA 0 VND'
END

-- update KHACHHANG
CREATE TRIGGER trg_update_kh_c15 ON KHACHHANG
AFTER UPDATE
AS BEGIN
	DECLARE @DOANHSO_CU MONEY, @DOANHSO_MOI MONEY
	SELECT @DOANHSO_CU = DOANHSO FROM DELETED
	SELECT @DOANHSO_MOI = DOANHSO FROM INSERTED
	IF (@DOANHSO_CU = @DOANHSO_MOI)
	BEGIN
		PRINT 'DA UPDATE KHACHHANG VOI DOANHSO KHONG DOI'
	END
	ELSE
	BEGIN
		PRINT 'UPDATE THAT BAI DO THAY DOI DOANHSO'
	END
END

-- insert HOADON
CREATE TRIGGER trg_insert_hd_c15 ON HOADON
AFTER INSERT
AS BEGIN
	DECLARE @MAKH CHAR(4), @DOANHSO MONEY, @TRIGIA MONEY
	SELECT @DOANHSO = DOANHSO FROM KHACHHANG
	SELECT @TRIGIA = TRIGIA, @MAKH = MAKH FROM inserted

	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO - @TRIGIA
	WHERE MAKH = @MAKH
	PRINT 'DA INSERT 1 HOADON VA UPDATE LAI DOANHSO CUA KHACHHANG TUONG UNR'
END

-- delete HOADON
CREATE TRIGGER trg_delete_hd_c15 ON HOADON
AFTER INSERT
AS BEGIN
	DECLARE @MAKH CHAR(4), @DOANHSO MONEY, @TRIGIA MONEY
	SELECT @MAKH = MAKH, @TRIGIA = TRIGIA FROM inserted
	SELECT @DOANHSO = DOANHSO FROM KHACHHANG

	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO - @TRIGIA
	WHERE MAKH = @MAKH
	
	PRINT 'DA DELETE 1 HOADON VA CAP NHAT LAI DOANHSO CUA KHACHHANG TUONG UNG'
END


-- update HOADON
CREATE TRIGGER trg_update_hd_c15 ON HOADON
AFTER INSERT
AS BEGIN
	DECLARE @MAKH_CU CHAR(4), @TRIGIA_CU MONEY,
			@MAKH_MOI CHAR(4), @TRIGIA_MOI MONEY
	SELECT @MAKH_CU = MAKH, @TRIGIA_CU = TRIGIA FROM deleted
	SELECT @MAKH_MOI = MAKH, @TRIGIA_MOI = TRIGIA FROM inserted

	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO - @TRIGIA_CU
	WHERE MAKH = @MAKH_CU
	UPDATE KHACHHANG
	SET DOANHSO = DOANHSO + @TRIGIA_MOI
	WHERE MAKH = @MAKH_MOI
END























