CREATE DATABASE QLGV
USE QLGV


CREATE TABLE HOCVIEN(
	MAHV CHAR(5) NOT NULL,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
	CONSTRAINT PK_HV PRIMARY KEY (MAHV)
)

CREATE TABLE LOP(
	MALOP CHAR(3) NOT NULL,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4),
	CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
)

CREATE TABLE KHOA(
	MAKHOA VARCHAR(4) NOT NULL,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
)

CREATE TABLE MONHOC(
	MAMH VARCHAR(10) NOT NULL,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4),
	CONSTRAINT PK_MH PRIMARY KEY (MAMH)
)

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10)
	CONSTRAINT PK_DK PRIMARY KEY (MAMH, MAMH_TRUOC)
)

CREATE TABLE GIAOVIEN(
	MAGV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4),
	CONSTRAINT PK_GV PRIMARY KEY (MAGV)
)

CREATE TABLE GIANGDAY(
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	CONSTRAINT PK_GD PRIMARY KEY (MALOP, MAMH)
)

CREATE TABLE KETQUATHI(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10)
	CONSTRAINT PK_KQT PRIMARY KEY (MAHV, MAMH, LANTHI)
)

------------------------------------------------------------------

ALTER TABLE HOCVIEN ADD CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE LOP ADD CONSTRAINT FK_LOP_HV FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV),
				CONSTRAINT FK_LOP_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_GV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE MONHOC ADD CONSTRAINT FK_MH_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE DIEUKIEN ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
						CONSTRAINT FK_DK_MHTRC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)

ALTER TABLE GIAOVIEN ADD CONSTRAINT FK_GV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE GIANGDAY ADD CONSTRAINT FK_GD_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
						CONSTRAINT FK_GD_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
						CONSTRAINT FK_GD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KETQUATHI ADD CONSTRAINT FK_KQT_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
						CONSTRAINT FK_KQT_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

-------------------------------------------------------------
ALTER TABLE HOCVIEN DROP CONSTRAINT CHK_MAHV_LOP
ALTER TABLE HOCVIEN DROP CONSTRAINT CHK_MAHV_STT

DROP TABLE KETQUATHI
DROP TABLE GIANGDAY
DROP TABLE GIAOVIEN
DROP TABLE DIEUKIEN
DROP TABLE MONHOC
DROP TABLE KHOA
DROP TABLE LOP
DROP TABLE HOCVIEN

----------------------------------------------------------------------

/* I. Ngon ngu dinh nghia du lieu */

-- 1. Them thuoc tinh GHICHU, DIEMTB, XEPLOAI cho quan he HOCVIEN
ALTER TABLE HOCVIEN ADD GHICHU VARCHAR(50),
						DIEMTB NUMERIC(4,2),
						XEPLOAI VARCHAR(10)

-- 2. Ma hv la 1 chuoi 5 ky tu, 3 ky tu dau la ma lop, 2 ky tu cuoi la STT hv
ALTER TABLE HOCVIEN ADD CONSTRAINT CHK_MAHV_LOP CHECK(LEFT(MAHV, 3) = MALOP)
ALTER TABLE HOCVIEN ADD CONSTRAINT CHK_MAHV_STT CHECK(RIGHT(MAHV, 2) >= '00' AND RIGHT(MAHV, 2) <= '99')

-- 3. Thuoc tinh GIOITINH chi co gia tri 'Nam' hoac 'Nu'
ALTER TABLE HOCVIEN ADD CONSTRAINT CHK_HV_GT CHECK (GIOITINH IN ('Nam', 'Nu'))
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHK_GV_GT CHECK (GIOITINH IN ('Nam', 'Nu'))

-- 4. Diem so cua 1 lan thi co gia tri tu 0 -> 10 va can luu den 2 so le
ALTER TABLE KETQUATHI ADD CONSTRAINT CHK_DIEM CHECK (DIEM >= 0 AND DIEM <= 10)

-- 5. KQT la 'Dat' neu diem tu 5 -> 10, 'Khong dat' neu diem < 5
ALTER TABLE KETQUATHI ADD CONSTRAINT CHK_KQT CHECK ((KQUA = 'Dat' AND DIEM >=5) OR (KQUA = 'Khong dat' AND DIEM < 5))

-- 6. HV thi 1 mon toi da 3 lan
ALTER TABLE KETQUATHI ADD CONSTRAINT CHK_LANTHI CHECK (LANTHI <= 3)

-- 7. Hoc ky co gia tri tu 1 -> 3
ALTER TABLE GIANGDAY ADD CONSTRAINT CHK_HK CHECK (HOCKY >=1 AND HOCKY <= 3)

-- 8. Hoc vi cua GV chi co the la 'CN', 'KS', 'Ths', 'TS', 'PTS'
ALTER TABLE GIAOVIEN ADD CONSTRAINT CHK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))


--------------------------------------------------------------------------------------------------


/* II. Ngon ngu thao tac du lieu */

-- 1.
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN ( SELECT TRGKHOA FROM KHOA )

-- 2.
UPDATE HOCVIEN
SET DIEMTB = (
	SELECT AVG(K1.DIEM)
	FROM KETQUATHI AS K1
	WHERE K1.LANTHI = (	SELECT MAX(K2.LANTHI) FROM KETQUATHI AS K2
						WHERE K2.MAHV = K1.MAHV AND K1.MAMH = K2.MAMH
						GROUP BY K2.MAMH, K2.MAMH )
	GROUP BY MAHV
	HAVING K1.MAHV = HOCVIEN.MAHV)



-- 3.
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN ( SELECT MAHV
				FROM KETQUATHI
				WHERE LANTHI = 3 AND DIEM < 5)



SET DATEFORMAT DMY





-----------------------------------------/* LAB 5: I.9 -> I.24 */------------------------------------------------------------------------------

-- 9. Lớp trưởng của một lớp phải là học viên của lớp đó. 
CREATE TRIGGER trg_insert_update_lop_c9 ON LOP
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @TRGLOP CHAR(5), @MALOP CHAR(3)
	SELECT @TRGLOP = TRGLOP, @MALOP = MALOP FROM inserted
	IF (@TRGLOP IN (	SELECT MAHV
						FROM HOCVIEN WHERE MALOP = @MALOP))
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'FAIL'
		ROLLBACK TRANSACTION
	END
END


-- 10. Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”. 
CREATE TRIGGER trg_insert_update_khoa_c10 ON KHOA
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @TRGKHOA CHAR(4), @MAKHOA CHAR(4)
	SELECT @TRGKHOA = TRGKHOA, @MAKHOA = MAKHOA FROM inserted
	IF (@TRGKHOA IN (	SELECT MAGV FROM GIAOVIEN
						WHERE MAKHOA = @MAKHOA
						AND HOCVI IN ('TS', 'PTS')))
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'TRGKHOA PHAI LA GIAO VIEN THUOC KHOA VA CO HOC VI "TS" HOAC "PTS"'
		ROLLBACK TRANSACTION
	END
END


-- 11. Học viên ít nhất là 18 tuổi. 
CREATE TRIGGER trg_insert_update_hv_c11 ON HOCVIEN
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @NGSINH SMALLDATETIME
	SELECT @NGSINH = NGSINH FROM inserted
	IF (DATEDIFF(YEAR, @NGSINH, CURRENT_TIMESTAMP) >= 18)
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'HOC VIEN IT NHAT LA 18 TUOI'
		ROLLBACK TRANSACTION
	END
END

-- 12. Giảng dạy một môn học ngày bắt đầu (TUNGAY) phải nhỏ hơn ngày kết thúc (DENNGAY). 
CREATE TRIGGER trg_insert_update_gd_c12 ON GIANGDAY
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @TUNGAY SMALLDATETIME, @DENNGAY SMALLDATETIME
	SELECT @TUNGAY = TUNGAY, @DENNGAY = DENNGAY FROM inserted
	IF (@TUNGAY >= @DENNGAY)
	BEGIN
		PRINT 'NGAY BAT DAU PHAI NHO HON NGAY KET THUC'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'SUCCESSFUL'
	END
END

-- 13. Giáo viên khi vào làm ít nhất là 22 tuổi. 
CREATE TRIGGER trg_insert_update_gv_c13 ON GIAOVIEN
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @NGSINH SMALLDATETIME, @NGVL SMALLDATETIME
	SELECT @NGSINH = NGSINH, @NGVL = NGVL FROM inserted
	IF (DATEDIFF(YEAR, @NGSINH, @NGVL) >= 22)
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'GIAO VIEN KHI VAO LAM IT NHAT LA 22 TUOI'
		ROLLBACK TRANSACTION
	END
END

-- 14. Tất cả các môn học đều có số tín chỉ lý thuyết và tín chỉ thực hành chênh lệch nhau không quá 3. 
CREATE TRIGGER trg_insert_ipdate_mh_c14 ON MONHOC
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @TCLT TINYINT, @TCTH TINYINT
	SELECT @TCLT = TCLT, @TCTH = TCTH FROM inserted
	IF (-3 <= (@TCLT - @TCTH) AND (@TCLT - @TCTH) <= 3)
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'TCLT VA TCTH CHENH LECH NHAU KHONG QUA 3'
		ROLLBACK TRANSACTION
	END
END

-- 15. Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này. 
--				THEM	XOA		SUA
-- GIANGDAY		 -		 -		 +
-- KETQUATHI	 +		 -		 +

-- update GIANGDAY
CREATE TRIGGER trg_update_gd_c15 ON GIANGDAY
AFTER UPDATE
AS BEGIN
	DECLARE @DENNGAY SMALLDATETIME, @NGTHI SMALLDATETIME
	SELECT @DENNGAY = DENNGAY, @NGTHI = NGTHI
	FROM inserted I, HOCVIEN HV, KETQUATHI K
	WHERE I.MALOP = HV.MALOP AND HV.MAHV = K.MAHV AND K.MAMH = I.MAMH
	IF (@DENNGAY < @NGTHI)
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'ERROR: NGAY KET THUC PHAI NHO HON NGAY THI'
		ROLLBACK TRANSACTION
	END
END

-- insert update KETQUATHI
ALTER TRIGGER trg_insert_update_c15 ON KETQUATHI
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @DENNGAY SMALLDATETIME, @NGTHI SMALLDATETIME
	SELECT @NGTHI = NGTHI, @DENNGAY = DENNGAY
	FROM inserted I, GIANGDAY GD, HOCVIEN HV
	WHERE I.MAMH = GD.MAMH AND I.MAHV = HV.MAHV AND HV.MALOP = GD.MALOP
	IF (@DENNGAY <@NGTHI)
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'ERROR: NGAY KET THUC PHAI NHO HON NGAY THI'
		ROLLBACK TRANSACTION
	END
END


-- 16. Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn. 
--				THEM	XOA		SUA
-- GIANGDAY		 +		 -		 +

CREATE TRIGGER trg_insert_update_gd_c16 ON GIANGDAY
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @SL_MH SMALLINT
	SELECT @SL_MH = COUNT(I.MAMH)
	FROM GIANGDAY GD, inserted I
	WHERE GD.MALOP = I.MALOP AND GD.HOCKY = I.HOCKY AND GD.NAM = I.NAM

	IF (@SL_MH > 3)
	BEGIN
		PRINT 'ERROR: LOP NAY CHI DUOC HOC 3 LAN TRONG CUNG HOCKY, NAM'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'SECCESSFUL'
	END
END



-- 17. Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó. 
--			THEM	XOA		SUA
-- LOP		 +		 -		 +
-- HOCVIEN	 +		 +		 +

CREATE TRIGGER trg_insert_lop_c17 ON LOP
AFTER INSERT
AS BEGIN
	UPDATE LOP
	SET SISO = 0
	WHERE MALOP = (	SELECT MALOP FROM inserted )
END

-------------------
ALTER TRIGGER trg_update_lop_c17 ON LOP
AFTER UPDATE
AS BEGIN
	DECLARE @SISO_CU TINYINT, @SISO_MOI TINYINT
	SELECT @SISO_CU = SISO FROM deleted
	SELECT @SISO_MOI = SISO FROM inserted
	IF (@SISO_CU = @SISO_MOI)
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'SISO LOP KHONG DUOC THAY DOI'
		ROLLBACK TRANSACTION
	END
END

-------------------
CREATE TRIGGER trg_insert_hv_c17 ON HOCVIEN
AFTER INSERT
AS BEGIN
	DECLARE @MALOP CHAR(3)
	SELECT @MALOP = MALOP FROM inserted
	UPDATE LOP
	SET SISO = SISO + 1
	WHERE MALOP = @MALOP

	PRINT 'DA UPDATE SISO CUA LOP TUONG UNG'
END
	
-------------------
CREATE TRIGGER trg_delete_hv_c17 ON HOCVIEN
AFTER INSERT
AS BEGIN
	DECLARE @MALOP CHAR(3), @SISO INT
	SELECT @MALOP = MALOP FROM inserted
	IF (@SISO > 0)
	BEGIN
		UPDATE LOP
		SET SISO = SISO - 1
		WHERE MALOP = @MALOP
	PRINT 'DA UPDATE SISO CUA LOP TUONG UNG'
	END
END

-------------------
CREATE TRIGGER trg_update_hv_c17 ON HOCVIEN
AFTER UPDATE
AS BEGIN
	DECLARE @MALOP_CU CHAR(3), @MALOP_MOI CHAR(3)
	SELECT @MALOP_CU = MALOP FROM deleted
	SELECT @MALOP_MOI = MALOP FROM deleted

	IF (@MALOP_CU <> @MALOP_MOI)
	BEGIN
		UPDATE LOP
		SET SISO = SISO - 1
		WHERE MALOP = @MALOP_CU
		UPDATE LOP
		SET SISO = SISO + 1
		WHERE MALOP = @MALOP_MOI

		PRINT 'DA UPDATE SISO CUA LOP TUONG UNG'
	END
END


-- 18. Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong cùng một bộ 
-- không được giống nhau (“A”,”A”) và cũng không tồn tại hai bộ (“A”,”B”) và (“B”,”A”). 
CREATE TRIGGER trg_insert_update_dk_c18 ON DIEUKIEN
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @MAMH VARCHAR(10), @MAMH_TRUOC VARCHAR(10)
	SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC FROM inserted
	
	IF ((@MAMH = @MAMH_TRUOC) OR
		(@MAMH IN (	SELECT MAMH_TRUOC FROM DIEUKIEN
					WHERE MAMH = @MAMH_TRUOC )) OR
		(@MAMH_TRUOC IN (	SELECT MAMH FROM DIEUKIEN
							WHERE MAMH_TRUOC = @MAMH	)))
	BEGIN
		PRINT 'ERROR: DIEUKIEN KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'SUCCESSFUL'
	END
END

-- 19. Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau. 
CREATE TRIGGER trg_insert_update_gv_c19 ON GIAOVIEN
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @MAGV CHAR(4), @MUCLUONG MONEY, @HOCHAM VARCHAR(10), @HOCVI VARCHAR(10)
	SELECT @MAGV = MAGV, @MUCLUONG = MUCLUONG, @HOCVI = HOCVI, @HOCHAM = HOCHAM
	FROM inserted

	UPDATE GIAOVIEN
	SET MUCLUONG = @MUCLUONG
	FROM GIAOVIEN GV
    JOIN inserted ID ON GV.HOCHAM = ID.HOCHAM AND GV.HOCVI = ID.HOCVI AND GV.HESO = ID.HESO
    WHERE GV.MAGV <> ID.MAGV
END


-- 20. Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5. 
CREATE TRIGGER trg_update_insert_kqt_c20 ON KETQUATHI
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @LANTHI TINYINT, @DIEM NUMERIC(4, 2)
	SELECT @LANTHI = LANTHI FROM inserted
	IF (@LANTHI > 1 )
	BEGIN
		IF ((	SELECT @DIEM FROM KETQUATHI K, inserted I
				WHERE I.MAHV = K.MAHV AND I.MAMH = K.MAMH AND K.LANTHI = @LANTHI-1) < 5)
		BEGIN 
			PRINT 'ERROR: HOCVIEN THI LAI KHI DIEM THI TRUOC DO DUOI 5'
			ROLLBACK TRANSACTION
		END
	END
	ELSE
	BEGIN
		PRINT 'SUCCESSFUL'
	END
END


-- 21. Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước (cùng học viên, cùng môn học). 
CREATE TRIGGER trg_insert_update_kqt_c21 ON KETQUATHI
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @NGTHI SMALLDATETIME, @MAHV CHAR(5), @MAMH VARCHAR(10), @LANTHI TINYINT
	SELECT @NGTHI = NGTHI, @MAHV = MAHV, @MAMH = MAMH, @LANTHI = LANTHI FROM inserted
	IF ((@LANTHI = 1) OR
	(@LANTHI > 1) AND (@NGTHI > ALL (	SELECT NGTHI FROM KETQUATHI
										WHERE MAHV = @MAHV AND MAMH = @MAMH)))
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'ERROR: NGAY THI LAN THI SAU PHAI LON HON NGAY THI LAN THI TRUOC'
		ROLLBACK TRANSACTION
	END
END

-- 22. Học viên chỉ được thi những môn mà lớp của học viên đó đã học xong. 
CREATE TRIGGER trg_insert_update_kqt_c22 ON KETQUATHI
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @DENNGAY SMALLDATETIME, @NGTHI SMALLDATETIME
	SELECT @NGTHI = NGTHI, @DENNGAY = DENNGAY
	FROM GIANGDAY GD, HOCVIEN HV, inserted I
	WHERE GD.MAMH = I.MAMH AND I.MAHV = HV.MAHV AND HV.MALOP = GD.MALOP

	IF (@NGTHI < @DENNGAY)
	BEGIN
		PRINT 'ERROR: NGAYTHI KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'SUCCESSFUL'
	END
END

-- 23. Khi phân công giảng dạy một môn học, phải xét đến thứ tự trước sau giữa các môn học 
-- (sau khi học xong những môn học phải học trước mới được học những môn liền sau). 
CREATE TRIGGER trg_insert_update_gd_c23 ON GIANGDAY
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @MAMH VARCHAR(10), @MALOP CHAR(3)
	SELECT @MAMH = MAMH, @MALOP = MALOP FROM inserted
	IF (@MAMH IN (	SELECT MAMH
					FROM DIEUKIEN
					WHERE MAMH_TRUOC IN (	SELECT MAMH
											FROM GIANGDAY
											WHERE MALOP = @MAMH	)))
	BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE
	BEGIN
		PRINT 'MAMH KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
END



-- 24. Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách. 
CREATE TRIGGER trg_insert_update_c24 ON GIANGDAY
AFTER INSERT, UPDATE
AS BEGIN
	DECLARE @MAKHOA1 CHAR(4), @MAKHOA2 CHAR(4)
	SELECT @MAKHOA1 = MH.MAKHOA, @MAKHOA2 = GV.MAKHOA
	FROM inserted I, GIAOVIEN GV, MONHOC MH
	WHERE MH.MAMH = I.MAMH AND GV.MAGV = I.MAGV

	IF (@MAKHOA1 <> @MAKHOA2)
	BEGIN
		PRINT 'ERROR: MAMH PHAI THUOC KHOA GIAO VIEN PHU TRACH'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'SUCCESSFUL'
	END
END











